# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Matlab
  version: 2012a
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Matlab
      url: /p1_landing_page.html
      output: web

    - title: Comandos 
      url: /p1_sample1.html
      output: web, pdf

    - title: DC Machine Simulation
      url: /p1_sample2.html
      output: web, pdf

    - title: Synchronous Machine Simulation
      url: /p1_sample3.html
      output: web, pdf

    - title: HIL
      url: /p1_sample4.html
      output: web, pdf

    - title: Electronics
      url: /p1_sample5.html
      output: web, pdf

    - title: More Issues
      url: /p1_sample6.html
      output: web, pdf


  - title: Another heading
    output: web, pdf

    folderitems:

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf
