# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Python
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Python-Entry-Level
    output: web, pdf
    folderitems:
    - title: Index 
      url: /python_00.html
      output: web, pdf
    - title: Py01
      url: /python_01.html
      output: web, pdf
    - title: Py02
      url: /python_02.html
      output: web, pdf

    - title: Py03
      url: /python_03.html
      output: web, pdf

    - title: Py04
      url: /python_04.html
      output: web, pdf

    - title: Py05
      url: /python_05.html
      output: web, pdf

    - title: Py06
      url: /python_06.html
      output: web, pdf

    - title: Py07
      url: /python_07.html
      output: web, pdf

    - title: Py08
      url: /python_08.html
      output: web, pdf

    - title: Py09
      url: /python_09.html
      output: web, pdf

    - title: Py10
      url: /python_10.html
      output: web, pdf

    - title: Py11
      url: /python_11.html
      output: web, pdf

    - title: Py12
      url: /python_12.html
      output: web, pdf

    - title: Py13
      url: /python_13.html
      output: web, pdf

    - title: p2 landing page
      url: /p2_landing_page.html
      output: web


  - title: Initial Workflow
    output: web, pdf
    folderitems:

    - title: Sample1
      url: /p2_sample1.html
      output: web, pdf

    - title: Sample2
      url: /p2_sample2.html
      output: web, pdf

    - title: Sample3
      url: /p2_sample3.html
      output: web, pdf

    - title: Sample4
      url: /p2_sample4.html
      output: web, pdf

    - title: Sample5
      url: /p2_sample5.html
      output: web, pdf

  - title: Complex Workflow
    output: web, pdf
    folderitems:

    - title: Sample 6
      url: /p2_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p2_sample7.html
      output: web, pdf

    - title: Sample 8
      url: /p2_sample8.html
      output: web, pdf

    - title: Sample 9
      url: /p2_sample9.html
      output: web, pdf

    - title: Sample 10
      url: /p2_sample10.html
      output: web, pdf

    - title: Sample 11
      url: /p2_sample11.html
      output: web, pdf

    - title: Sample 12
      url: /p2_sample12.html
      output: web, pdf

    - title: Sample 13
      url: /p2_sample13.html
      output: web, pdf

    - title: Sample 14
      url: /p2_sample14.html
      output: web, pdf
