# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Matlab Product2
  version: 2012
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter
 
  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: Matlab Product 1 home
      url: /p2_landing_page.html
      type: homepage
      output: web, pdf

    - title: Initial Workflow
      output: web, pdf
      folderitems:

    - title: Sample1
      url: /p2_sample1.html
      output: web, pdf

    - title: Sample2
      url: /p2_sample2.html
      output: web, pdf

    - title: Sample3
      url: /p2_sample3.html
      output: web, pdf

    - title: Sample4
      url: /p2_sample4.html
      output: web, pdf

    - title: Sample5
      url: /p2_sample5.html
      output: web, pdf

  - title: Complex Workflow
    output: web, pdf
    folderitems:

    - title: Sample 6 MATLAB
      url: /p2_sample6.html
      output: web, pdf

    - title: Sample 7 MATLAB
      url: /p2_sample7.html
      output: web, pdf

    - title: Sample 8 MATLAB
      url: /p2_sample8.html
      output: web, pdf

    - title: Sample 9 MATLAB
      url: /p2_sample9.html
      output: web, pdf

    - title: Sample 10 MATLAB
      url: /p2_sample10.html
      output: web, pdf

    - title: Sample 11 MATLAB
      url: /p2_sample11.html
      output: web, pdf

    - title: Sample 12 MATLAB
      url: /p2_sample12.html
      output: web, pdf

    - title: Sample 13 MATLAB
      url: /p2_sample13.html
      output: web, pdf

    - title: Sample 14 MATLAB
      url: /p2_sample14.html
      output: web, pdf
      