# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Python
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:

    - title: Python intro
      url: /p2_landing_page.html
      output: web

    - title: Python 6
      url: /p2_python6.html
      output: web, pdf

    - title: Python 7
      url: /p2_python7.html
      output: web, pdf

    - title: Python 8
      url: /p2_python8.html
      output: web, pdf

    - title: Python 9
      url: /p2_python9.html
      output: web, pdf

    - title: Python 10
      url: /p2_python10.html
      output: web, pdf

    - title: Python 11
      url: /p2_python11.html
      output: web, pdf

    - title: Python 12
      url: /p2_python12.html
      output: web, pdf


  - title: Initial Workflow
    output: web, pdf
    folderitems:

    - title: Fundamental Concepts
      url: /p2_sample1.html
      output: web, pdf

    - title: Literals, variables, and comments
      url: /p2_sample2.html
      output: web, pdf

    - title: Number Systems and Numeric Operators
      url: /p2_sample3.html
      output: web, pdf

    - title: Operators and Bindings
      url: /p2_sample4.html
      output: web, pdf

    - title: Input and Output Operations
      url: /p2_sample5.html
      output: web, pdf

  - title: Complex Workflow
    output: web, pdf
    folderitems:

    - title: Sample 6
      url: /p2_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p2_sample7.html
      output: web, pdf

    - title: Sample 8
      url: /p2_sample8.html
      output: web, pdf

    - title: Sample 9
      url: /p2_sample9.html
      output: web, pdf

    - title: Sample 10
      url: /p2_sample10.html
      output: web, pdf

    - title: Sample 11
      url: /p2_sample11.html
      output: web, pdf

    - title: Sample 12
      url: /p2_sample12.html
      output: web, pdf

    - title: Sample 13
      url: /p2_sample13.html
      output: web, pdf

    - title: Sample 14
      url: /p2_sample14.html
      output: web, pdf
